<section id="intro">
	<!-- Slider Setup -->

	<input checked="checked" name="slider" id="slide1" type="radio">
	<input name="slider" id="slide2" type="radio">
	<input name="slider" id="slide3" type="radio">
	<input name="slider" id="slide4" type="radio">
	<input name="slider" id="slide5" type="radio">
	
	
	<!-- The Slider -->
	
	<div id="slides">
	
		<div id="overflow">
		
			<div class="inner">
			
				<article>
					<div class="info"><h3>Underwather</h3> by <a href="http://www.elenakalisphoto.com">Elena Kalis</a></div>
					<img src="images/Underwather.jpg">
				</article>
				
				<article>
					<div class="info"><h3>Watch</h3> by <a href="http://mustafadedeoglu.deviantart.com/art/Watch-334803415">MustafaDedeogLu</a></div>
					<img src="images/Watch.jpg">
				</article>
				
				<article>
					<div class="info"><h3>Farmland Outpost</h3> by <a href="http://voyager3.tumblr.com/">Ariel Keiths</a></div>
					<img src="images/woman.jpg">
				</article>
				
				<article>
					<div class="info"><h3>Fake coke</h3> by <a href="http://halohid.deviantart.com/art/Fake-coke-90711229">Halohid</a></div>
					<img src="images/teens.jpg">
				</article>
				
				<article>
					<div class="info"><h3>Life in Salalah Beach</h3> by <a href="http://voyager3.tumblr.com/">Tenetsi</a></div>
					<img src="images/morale.jpg">
				</article>
				
			</div> <!-- .inner -->
			
		</div> <!-- #overflow -->
	
	</div> <!-- #slides -->
	
	
	<!-- Controls and Active Slide Display -->

	<div id="controls">

		<label for="slide1"></label>
		<label for="slide2"></label>
		<label for="slide3"></label>
		<label for="slide4"></label>
		<label for="slide5"></label>
	
	</div> <!-- #controls -->
	
	<div id="active">

		<label for="slide1"></label>
		<label for="slide2"></label>
		<label for="slide3"></label>
		<label for="slide4"></label>
		<label for="slide5"></label>
		
	</div> <!-- #active -->
</section>
		